instance_name       = "generative-ai"
instance_shape      = "VM.GPU.A10.1"
ssh_public_key_path = "server.key.pub"
subnet_cidr         = "10.0.0.0/24"
vcn_cidr            = "10.0.0.0/16"
region = "eu-frankfurt-1"
